[build]
target-dir = "target/rust/"
rustflags = ["--cfg", "tokio_unstable"]

[target.wasm32-unknown-unknown]
rustflags = [
  # Increas the stack size from 1MB to 2MB. This is required to avoid running out of stack space
  # in debug builds. The error is reported as `RuntimeError: memory access out of bounds`.
  "-C",
  "link-args=-z stack-size=2097152",
]

[alias]
cli="run --profile buildscript --target-dir target/enso-build --package enso-build-cli --bin enso-build-cli --"